micronaut:
  application:
    name: landetekotlin
  security:
    enabled: false
  cache:
    caffeine:
      default:
        maximum-size: 500
        expire-after-write: 1h
    caches:
      micache:
        maximum-size: 2000
        expire-after-write: 30m

netty:
  default:
    allocator:
      max-order: 3

endpoints:
  caches:
    enabled: true
